<?php

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

/**
 * Migration auto-generated by Sequel Pro Laravel Export (1.7.0)
 * @see https://github.com/cviebrock/sequel-pro-laravel-export
 */
class CreateTransDisposisiSuratTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('trans_disposisi_surat', function (Blueprint $table) {
            $table->bigIncrements('id');
            $table->unsignedBigInteger('id_surat_masuk')->default(0)->comment('Surat Masuk');
            $table->unsignedTinyInteger('id_arahan_surat')->default(0)->comment('Arahan surat');
            $table->unsignedTinyInteger('id_status_disposisi')->default(0)->comment('Status disposisi');
            $table->longText('ceklist_disposisi_surat')->collation('utf8mb4_bin')->default('')->comment('Ceklist disposisi surat');
            $table->text('catatan_surat')->default('')->comment('Catatan surat');
            $table->timestamps();
            $table->softDeletes();
            $table->index('id_surat_masuk', 'id_surat_masuk');
            $table->index('id_arahan_surat', 'id_arahan_surat');
            $table->index('id_status_disposisi', 'id_status_disposisi');

            $table->charset = 'utf8mb4';
            $table->collation = 'utf8mb4_general_ci';
        });
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('trans_disposisi_surat');
    }
}
