<?php

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

/**
 * Migration auto-generated by Sequel Pro Laravel Export (1.7.0)
 * @see https://github.com/cviebrock/sequel-pro-laravel-export
 */
class CreateTransDokumenSuratTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('trans_dokumen_surat', function (Blueprint $table) {
            $table->bigIncrements('id');
            $table->unsignedBigInteger('id_surat_masuk')->default(0)->comment('Surat Masuk');
            $table->string('nama_file', 250)->default('')->comment('Nama file');
            $table->unsignedTinyInteger('id_jenis_file')->default(0)->comment('Jenis file');
            $table->unsignedInteger('ukuran_file')->default(0)->comment('Ukuran File');
            $table->timestamps();
            $table->softDeletes();
            $table->index('id_surat_masuk', 'id_surat_masuk');
            $table->index('id_jenis_file', 'id_jenis_file');

            $table->charset = 'utf8mb4';
            $table->collation = 'utf8mb4_general_ci';
        });
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('trans_dokumen_surat');
    }
}
