<?php

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

/**
 * Migration auto-generated by Sequel Pro Laravel Export (1.7.0)
 * @see https://github.com/cviebrock/sequel-pro-laravel-export
 */
class CreateTransFileSuratKeluarTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('trans_file_surat_keluar', function (Blueprint $table) {
            $table->bigIncrements('id');
            $table->unsignedBigInteger('id_surat_keluar')->default(0)->comment('Surat Keluar');
            $table->unsignedTinyInteger('id_jenis_dokumen')->default(0)->comment('Jenis dokumen');
            $table->string('nama_file', 250)->default('')->comment('Nama file');
            $table->unsignedTinyInteger('id_jenis_file')->default(0)->comment('Jenis file');
            $table->unsignedInteger('ukuran_file')->default(0)->comment('Ukuran File');
            $table->timestamps();
            $table->softDeletes();
            $table->index('id_surat_keluar', 'id_surat_keluar');
            $table->index('id_jenis_dokumen', 'id_jenis_dokumen');
            $table->index('id_jenis_file', 'id_jenis_file');

            $table->charset = 'utf8mb4';
            $table->collation = 'utf8mb4_general_ci';
        });
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('trans_file_surat_keluar');
    }
}
