<?php

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

/**
 * Migration auto-generated by Sequel Pro Laravel Export (1.7.0)
 * @see https://github.com/cviebrock/sequel-pro-laravel-export
 */
class CreateTransSuratMasukTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('trans_surat_masuk', function (Blueprint $table) {
            $table->bigIncrements('id');
            $table->string('asal_surat_masuk', 250)->default('')->comment('Asal surat masuk');
            $table->string('pejabat_pengirim_surat', 250)->default('')->comment('Pejabat pengirim surat');
            $table->string('nomor_surat', 50)->default('')->comment('Nomor surat');
            $table->date('tanggal_surat')->comment('Tanggal surat');
            $table->string('kepada', 250)->default('')->comment('Kepada');
            $table->string('perihal', 250)->default('')->comment('Perihal');
            $table->unsignedTinyInteger('id_sifat_keamanan_surat')->default(0)->comment('Sifat keamanan surat');
            $table->unsignedTinyInteger('id_sifat_penyelesaian_surat')->default(0)->comment('Sifat penyelesaian surat');
            $table->date('tenggat_waktu_tindak_lanjut')->comment('Tenggat waktu tindak lanjut');
            $table->time('mulai_pukul')->comment('Mulai pukul');
            $table->string('nomor_agenda', 50)->default('')->comment('Nomor agenda');
            $table->date('tanggal_agenda')->comment('Tanggal agenda');
            $table->unsignedTinyInteger('id_asal_ekspedisi_surat_masuk')->default(0)->comment('Asal ekspedisi surat masuk');
            $table->string('email_pengirim', 250)->default('')->comment('Email pengirim');
            $table->string('alamat_pengirim', 250)->default('')->comment('Alamat pengirim');
            $table->unsignedTinyInteger('id_jenis_surat')->default(0)->comment('Jenis surat masuk');
            $table->timestamps();
            $table->softDeletes();
            $table->index('id_sifat_keamanan_surat', 'id_sifat_keamanan_surat');
            $table->index('id_sifat_penyelesaian_surat', 'id_sifat_penyelesaian_surat');
            $table->index('id_asal_ekspedisi_surat_masuk', 'id_asal_ekspedisi_surat_masuk');
            $table->index('id_jenis_surat', 'id_jenis_surat');

            $table->charset = 'utf8mb4';
            $table->collation = 'utf8mb4_general_ci';
        });
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('trans_surat_masuk');
    }
}
