<?php

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

/**
 * Migration auto-generated by Sequel Pro Laravel Export (1.7.0)
 * @see https://github.com/cviebrock/sequel-pro-laravel-export
 */
class CreateTrefUnitTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('tref_unit', function (Blueprint $table) {
            $table->increments('id');
            $table->unsignedInteger('id_unit')->default(0)->comment('Parent ID');
            $table->string('unit', 250)->default('')->comment('Unit');
            $table->string('jabatan', 250)->default('')->comment('Jabatan');
            $table->timestamps();
            $table->softDeletes();
            $table->index('id_unit', 'id_unit');

            $table->charset = 'utf8mb4';
            $table->collation = 'utf8mb4_general_ci';
        });
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('tref_unit');
    }
}
